#PATHS
resource_dir: /nfs/users/nfs_a/as33/Projects/MrMosaic/resources/
reference_dir: /lustre/scratch113/projects/ddd/users/as33/MrMosaic/test_data/
output_dir: /lustre/scratch113/projects/ddd/users/as33/MrMosaic/test_results/
